# This is a basic workflow to help you get started with Actions

name: build package

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: '14'
          
          
      # Runs a single command using the runners shell
      - name: Setup Chocolatey
        uses: crazy-max/ghaction-chocolatey@v1.6.0
        with:
            args: -h
      

      # Runs a single command using the runners shell
      - name: Installing Windows Build Tool
        run:  choco install python visualstudio2017-workload-vctools -y
        
      - name: Setting Up 2017 Vcode in NPM
        run: npm config set msvs_version 2017
             
       
       # Runs a single command using the runners shell
      - name: Installing Node dependency
        run: npm install -g node-gyp
        

        #DELETE THIS PLEASE
      - name: Install VSCode Extention
        working-directory: ./node
        run: npm install
        
      - name: reverting back to Old
        working-directory: ../
        run: pwd
        
        # Dlete This
       
      - name: Installing ESY
        run: npm install -g esy@latest
        
      - name: Installing ESY Packages
        run: esy install
        
      - name: Installing ESP Bootstrap
        run: esy bootstrap
               
      - name: Building Remaining Files
        run: esy build
        
      - name: Checking Build ( Health Check)
        run: esy run -f --checkhealth


       
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          Ready,
          npm config set msvs_version 2017,
          echo test, and deploy your project.
